name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: clone chromium
      run: |
        git clone https://github.com/chromium/chromium \
          --filter=blob:none \
          --single-branch \
          --sparse \
          --progress \
          --verbose

    - name: backfill chromedriver blobs
      run: |
        cd chromium
        git sparse-checkout set chrome/test/chromedriver
        git backfill --sparse

    - name: extract chromedriver history
      run: |
        git init -b main chromedriver
        (cd chromium && python3 ../extract_chromedriver.py) | git -C chromedriver fast-import --done

    - name: push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd chromedriver
        git config --global user.email "8435085+T3-M4@users.noreply.github.com"
        git config --global user.name  "T3-M4"
        git remote add chromedriver https://T3-M4:${GITHUB_TOKEN}@github.com/bayandin/chromedriver.git

        DRY_RUN=$([[ "${GITHUB_EVENT_NAME}" == "pull_request" ]] && echo "--dry-run" || echo "")
        git push --set-upstream chromedriver main ${DRY_RUN}
