name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Cleanup
      run: |
        # The step is copied from
        # - https://github.com/nodejs/node/blob/3b34fd77f27d074d606c95cda861e91d52deac84/.github/workflows/test-macos.yml
        # - https://github.com/AstarNetwork/Astar/blob/da7e689dd0dccd061d15cd5dbdf22aee5a86b2bb/.github/workflows/release-client.yml

        echo "::group::Free space before cleanup"
        df -h
        echo "::endgroup::"
        echo "::group::Cleaned Files"

        xcrun simctl delete all || true
        sudo rm -rf ~/Library/Developer/CoreSimulator/Caches/* || true
        sudo rm -rf /Users/runner/Library/Android/sdk || true
        sudo rm -rf /Applications/Xcode_* || true

        echo "::endgroup::"
        echo "::group::Free space after cleanup"
        df -h
        echo "::endgroup::"

    - name: clone chromium
      run: |
        git clone --filter=blob:none --single-branch --sparse --progress --verbose \
          https://github.com/chromium/chromium

    - name: backfill chromedriver blobs
      working-directory: chromium
      run: |
        git sparse-checkout set chrome/test/chromedriver
        git backfill --sparse

    - name: extract chromedriver history
      run: |
        git init -b main chromedriver
        (cd chromium && python3 ../extract_chromedriver.py) | git -C chromedriver fast-import --done

    - name: push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      working-directory: chromedriver
      run: |
        git config --global user.email "8435085+T3-M4@users.noreply.github.com"
        git config --global user.name  "T3-M4"
        git remote add chromedriver https://T3-M4:${GITHUB_TOKEN}@github.com/bayandin/chromedriver.git
        git push --force --set-upstream chromedriver main
